services:
  - type: worker
    name: faphouse-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
